package sa_b_2.coms309.dungeonadventure.ui.Activities;

import android.animation.Animator;
import android.animation.AnimatorListenerAdapter;
import android.annotation.TargetApi;
import android.content.Context;
import android.os.AsyncTask;
import android.os.Build;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.support.v7.app.AppCompatActivity;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.inputmethod.EditorInfo;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;

import sa_b_2.coms309.dungeonadventure.R;
import sa_b_2.coms309.dungeonadventure.game.Constants;
import sa_b_2.coms309.dungeonadventure.network.HttpParse;

/**
 * A Change password screen
 * 99% of this was generated by android studio
 */
public class ChangePasswordActivity extends AppCompatActivity {

    /**
     * Keep track of the login task to ensure we can cancel it if requested.
     */
    @Nullable
    private UserChangePasswordTask mAuthTask = null;

    // UI references.
    private EditText mCurrentPasswordView;
    private EditText mNewPasswordView;
    private EditText mConfirmPasswordView;
    private View mProgressView;
    private View mLoginFormView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_change_password);
        // Set up the login form.
        mCurrentPasswordView = (EditText) findViewById(R.id.current_password);

        mNewPasswordView = (EditText) findViewById(R.id.new_password);
        mConfirmPasswordView = (EditText) findViewById(R.id.new_password_confirm);
        mConfirmPasswordView.setOnEditorActionListener(new TextView.OnEditorActionListener() {
            @Override
            public boolean onEditorAction(TextView textView, int id, KeyEvent keyEvent) {
                if (id == R.id.change_pass || id == EditorInfo.IME_NULL) {
                    attemptChangePassword();
                    return true;
                }
                return false;
            }
        });

        Button mChangePasswordButton = (Button) findViewById(R.id.change_password_button);
        mChangePasswordButton.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View view) {
                attemptChangePassword();
            }
        });

        mLoginFormView = findViewById(R.id.login_form);
        mProgressView = findViewById(R.id.login_progress);
    }


    /**
     * Attempts to sign in or register the account specified by the login form.
     * If there are form errors (invalid email, missing fields, etc.), the
     * errors are presented and no actual login attempt is made.
     */
    private void attemptChangePassword() {
        if (mAuthTask != null)
            return;

        // Reset errors.
        mCurrentPasswordView.setError(null);
        mNewPasswordView.setError(null);
        mConfirmPasswordView.setError(null);

        // Store values at the time of the login attempt.
        String current = mCurrentPasswordView.getText().toString();
        String password = mNewPasswordView.getText().toString();
        String confirm = mConfirmPasswordView.getText().toString();

        boolean cancel = false;
        View focusView = null;

        if (!password.equals(confirm)) {
            mConfirmPasswordView.setError(getString(R.string.error_passwords_do_not_match));
            focusView = mConfirmPasswordView;
            cancel = true;
        }

        if (!isPasswordValid(password)) {
            mNewPasswordView.setError(getString(R.string.error_invalid_password));
            focusView = mNewPasswordView;
            cancel = true;
        }

        if (cancel) {
            // There was an error; don't attempt login and focus the first
            // form field with an error.
            focusView.requestFocus();
        } else {
            // Show a progress spinner, and kick off a background task to
            // perform the user login attempt.
            showProgress(true);
            mAuthTask = new UserChangePasswordTask(current, password);
            mAuthTask.execute((Void) null);
        }
    }

    private boolean isPasswordValid(@NonNull String password) {
        return password.length() > 6;
    }

    /**
     * Shows the progress UI and hides the login form.
     */
    @TargetApi(Build.VERSION_CODES.HONEYCOMB_MR2)
    private void showProgress(final boolean show) {
        // On Honeycomb MR2 we have the ViewPropertyAnimator APIs, which allow
        // for very easy animations. If available, use these APIs to fade-in
        // the progress spinner.
        int shortAnimTime = getResources().getInteger(android.R.integer.config_shortAnimTime);

        mLoginFormView.setVisibility(show ? View.GONE : View.VISIBLE);
        mLoginFormView.animate().setDuration(shortAnimTime).alpha(
                show ? 0 : 1).setListener(new AnimatorListenerAdapter() {
            @Override
            public void onAnimationEnd(Animator animation) {
                mLoginFormView.setVisibility(show ? View.GONE : View.VISIBLE);
            }
        });

        mProgressView.setVisibility(show ? View.VISIBLE : View.GONE);
        mProgressView.animate().setDuration(shortAnimTime).alpha(
                show ? 1 : 0).setListener(new AnimatorListenerAdapter() {
            @Override
            public void onAnimationEnd(Animator animation) {
                mProgressView.setVisibility(show ? View.VISIBLE : View.GONE);
            }
        });
    }

    /**
     * Represents an asynchronous login/registration task used to authenticate
     * the user.
     */
    private class UserChangePasswordTask extends AsyncTask<Void, Void, Boolean> {

        private final String mCurrentPassword;
        private final String mNewPassword;
        private int response = -1;

        UserChangePasswordTask(String current, String password) {
            mCurrentPassword = current;
            mNewPassword = password;
        }

        @NonNull
        @Override
        protected Boolean doInBackground(Void... params) {
            HashMap<String, String> map = new HashMap<>();
            map.put("username", Constants.currentUser.getUsername());
            map.put("oldPassword", mCurrentPassword);
            map.put("newPassword", mNewPassword);

            String loginURL = "http://proj-309-sa-b-2.cs.iastate.edu/ChangePassword.php";
            String finalResult = HttpParse.postRequest(map, loginURL);

            if (finalResult.equals("Something Went Wrong")) {
                response = 2;
                return false;
            }
            if (finalResult.equals("Not connected to the internet"))
                return false;

            response = Integer.parseInt(finalResult);

            return response == 0;
        }

        @Override
        protected void onPostExecute(final Boolean success) {
            mAuthTask = null;
            showProgress(false);

            if (success) {

                ArrayList<Byte> bytes = new ArrayList<>();
                FileInputStream fis;
                try {
                    fis = openFileInput(Constants.ACCOUNT_FILE);
                    while (fis.available() > 0)
                        bytes.add((byte) fis.read());
                    fis.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }

                byte[] b = new byte[bytes.size()];
                for (int z = 0; z < bytes.size(); ++z)
                    b[z] = bytes.get(z);

                String string = new String(b, StandardCharsets.UTF_8);

                if (string.length() > 1) {
                    try {
                        FileOutputStream fos;
                        fos = openFileOutput(Constants.ACCOUNT_FILE, Context.MODE_PRIVATE);
                        String write = Constants.currentUser.getUsername() + " " + mNewPassword;
                        fos.write(write.getBytes());
                        fos.close();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }

                finish();
            } else
                switch (response) {
                    case -1:
                        mCurrentPasswordView.setError(getString(R.string.error_internet_connection));
                        mCurrentPasswordView.requestFocus();
                        break;
                    case 0:
                        mCurrentPasswordView.setError(getString(R.string.error_bad_code));
                        mCurrentPasswordView.requestFocus();
                        break;
                    case 1:
                        mCurrentPasswordView.setError(getString(R.string.error_old_password_incorrect));
                        mCurrentPasswordView.requestFocus();
                        break;
                    case 2:
                    case 3:
                        mCurrentPasswordView.setError(getString(R.string.error_server_error));
                        mCurrentPasswordView.requestFocus();
                        break;
                }
        }

        @Override
        protected void onCancelled() {
            mAuthTask = null;
            showProgress(false);
        }
    }
}

